import type { CharacterData } from './types';

/** The Emotional Path's characters. */
export const EMOTIONAL = {
  oren: {
    number: 72,
    rarity: 5,
    name: 'Oren',
    fullName: 'Oren Stillwater',
    dimension: 'emotional',
    kind: 'core',
    unlockLevel: 0,
    bio: 'Tall, barefoot and shaven-headed, with calm eyes and a string of prayer beads that is missing one. He speaks rarely, and when he does, it is usually deadpan.',
    quote: 'Breathe first. Then we decide who to punch.',
  },
  juniper: {
    number: 42,
    rarity: 5,
    name: 'Juniper',
    fullName: 'Juniper Wick',
    dimension: 'emotional',
    kind: 'recruit',
    unlockLevel: 10,
    bio: 'A potter who throws clay when she is angry and keeps whatever survives the kiln. Her shelves are full of lopsided cups, and she loves every one.',
    quote: 'Cracked is still a cup.',
  },
  corwin: {
    number: 95,
    rarity: 5,
    name: 'Captain Corwin',
    dimension: 'emotional',
    kind: 'steward',
    unlockLevel: 15,
    bio: 'Scarred, in a red cloak and battered armor. Righteous, bitter and disciplined, he is loyal to a grudge above all else. Something about his face seems familiar.',
    quote: "I'm not angry. I'm correct.",
  },
  lark: {
    number: 94,
    rarity: 5,
    name: 'Lark',
    dimension: 'emotional',
    kind: 'recruit',
    unlockLevel: 20,
    bio: 'A stable hand who calms frightened horses by breathing slowly beside them. It works on people too, though they rarely notice it happening.',
    quote: 'In for four. Out for four. There. Better.',
  },
  dot: {
    number: 45,
    rarity: 5,
    name: 'Dot',
    dimension: 'emotional',
    kind: 'recruit',
    unlockLevel: 7,
    bio: 'A little girl with pigtails and a paper journal in which she rates her feelings out of five, in crayon. She is the most emotionally honest person in the party and says so.',
    quote: 'Today I am a four out of five. Mostly.',
  },
  rowan: {
    number: 16,
    rarity: 5,
    name: 'Rowan',
    fullName: 'Rowan Ashdown',
    dimension: 'emotional',
    kind: 'recruit',
    unlockLevel: 13,
    bio: 'The captain of a village bucket brigade, with a soot-streaked face and a steady voice. When everyone else panics, Rowan gets calmer, and it is contagious.',
    quote: 'Panic later. Water now.',
  },
  mireille: {
    number: 22,
    rarity: 5,
    name: 'Mireille',
    dimension: 'emotional',
    kind: 'recruit',
    unlockLevel: 18,
    bio: 'A mime with a painted white face and a striped shirt who expresses absolutely everything without a word. Her silent hugs are, by general agreement, the best in the land.',
    quote: "(She mimes a hug. It's a very good one.)",
  },
  teodor: {
    number: 86,
    rarity: 5,
    name: 'Teodor',
    fullName: 'Teodor Grim',
    dimension: 'emotional',
    kind: 'recruit',
    unlockLevel: 23,
    bio: 'A gravedigger in a long dark coat who whistles while he works and is completely at ease with sadness. People tell him things they have never told anyone.',
    quote: 'Grief is just love with nowhere to go. I give it somewhere.',
  },
  nell: {
    number: 43,
    rarity: 5,
    name: 'Nell',
    fullName: 'Nell Honeysuckle',
    dimension: 'emotional',
    kind: 'recruit',
    unlockLevel: 26,
    bio: 'A gardener in a sun hat covered in pollen who talks to her plants about her day, every day. She insists the roses give excellent advice.',
    quote: "The roses know everything. They're very discreet.",
  },
  bartholomew: {
    number: 7,
    rarity: 5,
    name: 'Bartholomew',
    dimension: 'emotional',
    kind: 'recruit',
    unlockLevel: 30,
    bio: 'A large brown bear with a soft voice and an even softer heart, who communicates mostly through hugs. He is very careful with his claws.',
    quote: 'Hug? Hug.',
  },
  iris: {
    number: 79,
    rarity: 5,
    name: 'Iris',
    fullName: 'Iris Calloway',
    dimension: 'emotional',
    kind: 'recruit',
    unlockLevel: 35,
    bio: 'A former soldier with a long scarf and a soft voice, learning to sleep through the night again. She is patient with herself in a way that makes others patient with themselves too.',
    quote: 'Some days are heavy. I carry them, and set them down at night.',
  },
  willa: {
    number: 54,
    rarity: 5,
    name: 'Willa',
    fullName: 'Willa Stillpond',
    dimension: 'emotional',
    kind: 'recruit',
    unlockLevel: 40,
    bio: 'A fisherwoman in a yellow raincoat who can sit by the water for hours without a flicker of impatience. She catches less than anyone and is happier about it than anyone.',
    quote: 'The fish come when you stop needing them to.',
  },
  kaito: {
    number: 40,
    rarity: 5,
    name: 'Master Kaito',
    dimension: 'emotional',
    kind: 'legend',
    unlockLevel: 50,
    bio: 'An ancient teacher with a beard to his belt and a single brush he paints one stroke with each morning. He has felt every feeling there is and is afraid of none of them.',
    quote: 'Feel it all. Then choose.',
  },
} satisfies Record<string, CharacterData>;
