import type { CharacterData } from './types';

/** The Environmental Path's characters. */
export const ENVIRONMENTAL = {
  moss: {
    number: 52,
    rarity: 5,
    alignment: 'Chaotic Good',
    name: 'Moss',
    dimension: 'environmental',
    kind: 'core',
    unlockLevel: 0,
    bio: 'Lanky, with leaves in his hair and a bark-colored cloak, Moss travels with a one-eared fox called Tuft. Quiet around people, chatty with animals, and never quite where you left him.',
    quote: "Tuft says you're alright. Tuft is usually wrong. We'll see.",
  },
  fern: {
    number: 27,
    rarity: 5,
    alignment: 'Neutral Good',
    name: 'Fern',
    fullName: 'Fern Ashby',
    dimension: 'environmental',
    kind: 'recruit',
    unlockLevel: 10,
    bio: 'A beekeeper with a hat full of holes and a very patient hive. She walks slowly, speaks softly and has not been stung in years.',
    quote: "They're not angry. They're busy. Big difference.",
  },
  brimsby: {
    number: 65,
    rarity: 5,
    alignment: 'Neutral',
    name: 'Mother Brimsby',
    dimension: 'environmental',
    kind: 'steward',
    unlockLevel: 15,
    bio: 'A vast, kindly innkeeper in a flour-dusted apron, whose feast table stretches for miles. Warm, grandmotherly and relentlessly hospitable, she will not take no for an answer.',
    quote: 'Eat, eat. There is always more. There will always be more.',
  },
  tully: {
    number: 32,
    rarity: 5,
    alignment: 'Chaotic Good',
    name: 'Old Tully',
    dimension: 'environmental',
    kind: 'recruit',
    unlockLevel: 20,
    bio: 'A ferryman who knows every bird on the river by its song, and fishes litter out of the water with a long-handled net.',
    quote: 'The river gives if you let it. Mostly it gives boots.',
  },
  sprout: {
    number: 18,
    rarity: 5,
    alignment: 'Chaotic Good',
    name: 'Sprout',
    dimension: 'environmental',
    kind: 'recruit',
    unlockLevel: 7,
    bio: 'A small, earnest child with a leaf growing out of their hat who insists they grow a little every day. Sprout waters themself with great ceremony every morning.',
    quote: 'I grow a little every day. Watch! ...Okay, not that fast.',
  },
  cora: {
    number: 11,
    rarity: 5,
    alignment: 'Neutral Good',
    name: 'Cora',
    fullName: 'Cora Glen',
    dimension: 'environmental',
    kind: 'recruit',
    unlockLevel: 13,
    bio: 'A shepherd with a wooden crook and a flock of very fluffy sheep who follow her everywhere, including indoors. She knows every sheep by name and personality.',
    quote: 'Count the sheep, not the worries.',
  },
  rufus: {
    number: 6,
    rarity: 5,
    alignment: 'Chaotic Neutral',
    name: 'Rufus',
    dimension: 'environmental',
    kind: 'recruit',
    unlockLevel: 18,
    bio: 'A raccoon with a little sack who tidies up every scrap of litter he finds, and keeps the shiniest pieces for himself. Mischievous, thorough and very proud of his work.',
    quote: "One person's trash is my whole hobby.",
  },
  wynn: {
    number: 91,
    rarity: 5,
    alignment: 'Chaotic Neutral',
    name: 'Wynn',
    fullName: 'Wynn Rainmaker',
    dimension: 'environmental',
    kind: 'recruit',
    unlockLevel: 23,
    bio: 'A weather-watcher with a patched umbrella and a barometer on a string, who can smell rain coming a day away. They think storms are beautiful and say so loudly.',
    quote: "Rain isn't bad weather. It's the sky watering its garden.",
  },
  tala: {
    number: 25,
    rarity: 5,
    alignment: 'Lawful Good',
    name: 'Tala',
    fullName: 'Tala Riverstone',
    dimension: 'environmental',
    kind: 'recruit',
    unlockLevel: 26,
    bio: 'A canoe guide with a paddle over her shoulder who fishes every scrap of rubbish out of the river as she goes. She leaves every bend of it cleaner than she found it.',
    quote: 'Leave it better than you found it. Every bend.',
  },
  hugo: {
    number: 17,
    rarity: 5,
    alignment: 'Lawful Neutral',
    name: 'Hugo',
    fullName: 'Hugo Thornbeard',
    dimension: 'environmental',
    kind: 'recruit',
    unlockLevel: 30,
    bio: 'A huge, gentle gardener with a green beard and shears, who once pruned the royal hedge maze and now tends wild roses. He is very, very patient with thorns.',
    quote: 'Snip. Breathe. Snip.',
  },
  antler: {
    number: 49,
    rarity: 5,
    alignment: 'Chaotic Good',
    name: 'Old Antler',
    dimension: 'environmental',
    kind: 'recruit',
    unlockLevel: 35,
    bio: 'A great white stag with antlers like a winter tree, who appears at the edge of clearings and bows to those who walk softly. Nobody has ever heard him speak.',
    quote: '(He bows his head. The forest goes quiet.)',
  },
  ivy: {
    number: 48,
    rarity: 5,
    alignment: 'Neutral Good',
    name: 'Ivy',
    fullName: 'Ivy Greenmantle',
    dimension: 'environmental',
    kind: 'recruit',
    unlockLevel: 40,
    bio: 'A druid wrapped in a cloak of living vines that flower when she laughs. She believes everything in the world is connected, and she will explain how at length.',
    quote: 'Everything is connected. Especially your shoelaces. Tie them.',
  },
  warden: {
    number: 30,
    rarity: 5,
    alignment: 'True Neutral',
    name: 'The Green Warden',
    dimension: 'environmental',
    kind: 'legend',
    unlockLevel: 50,
    bio: 'An ancient guardian of the forest, made of bark and moss, with branches for antlers and eyes like fireflies. It has waited a very long time for someone to walk this Path again.',
    quote: 'I have waited a long time for someone to walk this Path again.',
  },
} satisfies Record<string, CharacterData>;
