import type { CharacterData } from './types';

/** The Financial Path's characters. */
export const FINANCIAL = {
  ysolde: {
    name: 'Ysolde',
    fullName: 'Ysolde Marrow',
    dimension: 'financial',
    kind: 'core',
    unlockLevel: 0,
    bio: 'A faded silk gown patched with sacking, a cracked monocle and a ledger chained to her belt. Sharp, dry and disciplined, she trusts numbers over people and keeps score in every friendship. Somehow the tab always comes out in your favor.',
    quote: 'Charming. Now, what does it cost?',
  },
  penny: {
    name: 'Penny',
    fullName: 'Penny Vell',
    dimension: 'financial',
    kind: 'recruit',
    unlockLevel: 10,
    bio: 'A sharp-eyed market kid who can price a turnip from across the square. She keeps her savings in her left boot and has never once been cheated.',
    quote: "A copper saved is a copper you don't have to find.",
  },
  tithe: {
    name: 'Countess Tithe',
    fullName: 'Countess Constance Tithe',
    dimension: 'financial',
    kind: 'steward',
    unlockLevel: 15,
    bio: 'Dripping in jewels, she carries a set of golden scales and owns the Counting House. Elegant and charming, she never raises her voice, and she has a price for everything.',
    quote: 'Nothing is free, darling. Least of all hope.',
  },
  aubrey: {
    name: 'Lord Aubrey',
    fullName: 'Lord Aubrey Finch',
    dimension: 'financial',
    kind: 'recruit',
    unlockLevel: 20,
    bio: 'A nervous minor lord who inherited a crumbling estate and a very long list of debts. He is learning to budget from a book he could not really afford.',
    quote: "I've made a ledger. It's terrifying.",
  },
  wendel: {
    name: 'Wendel',
    fullName: 'Wendel Coin',
    dimension: 'financial',
    kind: 'recruit',
    unlockLevel: 7,
    bio: 'A bridge tollkeeper with enormous spectacles and a green visor, who counts coppers into neat little towers. Fussy, fair and secretly delighted whenever the numbers add up.',
    quote: 'Two for the bridge. One for the troll. Kidding. No troll.',
  },
  saoirse: {
    name: 'Saoirse',
    fullName: 'Saoirse Thrift',
    dimension: 'financial',
    kind: 'recruit',
    unlockLevel: 13,
    bio: 'A seamstress in a dress patched from a dozen old favorites, with pins lined up along her collar. She mends everything rather than replace it, and she can tell you the story of every patch.',
    quote: 'Why buy new when the old one has stories?',
  },
  hamish: {
    name: 'Hamish',
    fullName: 'Hamish Budge',
    dimension: 'financial',
    kind: 'recruit',
    unlockLevel: 18,
    bio: 'A round, rosy pig farmer in muddy overalls who has been saving for a second pig for three years. He keeps his accounts in chalk on the barn door and is extremely proud of them.',
    quote: 'The second pig is a long-term investment.',
  },
  priya: {
    name: 'Priya',
    fullName: 'Priya Ledgerlight',
    dimension: 'financial',
    kind: 'recruit',
    unlockLevel: 23,
    bio: 'The accountant of a caravan that stopped mid-journey, in an orange silk headscarf with a brass abacus at her hip. She is warm, brisk and utterly unimpressed by anyone who says they will pay later.',
    quote: "Numbers don't lie. People do, a bit.",
  },
  gus: {
    name: 'Gus',
    fullName: 'Gus Tallow',
    dimension: 'financial',
    kind: 'recruit',
    unlockLevel: 26,
    bio: 'A candle-maker in a waxy apron who has never wasted a single drip. He melts every stub back into a new candle and keeps the shop warm on almost nothing.',
    quote: 'Every stub becomes a new candle.',
  },
  mirela: {
    name: 'Mirela',
    fullName: 'Mirela Goldvein',
    dimension: 'financial',
    kind: 'recruit',
    unlockLevel: 30,
    bio: 'A miner turned banker, still in her yellow hard hat with its little lamp, flashing one gold tooth when she grins. She knows exactly how hard every coin was to dig up, and spends accordingly.',
    quote: 'Dig slow. Spend slower.',
  },
  ambrose: {
    name: 'Ambrose',
    fullName: 'Ambrose Tally',
    dimension: 'financial',
    kind: 'recruit',
    unlockLevel: 35,
    bio: 'A vault guard with a key ring the size of a dinner plate, who has guarded more gold than anyone alive and never wanted a single coin of it. Solemn, honest and fond of very bad puns.',
    quote: "I guard it. I don't want it. That's the whole job.",
  },
  marchbank: {
    name: 'Lady Marchbank',
    dimension: 'financial',
    kind: 'recruit',
    unlockLevel: 40,
    bio: 'An elderly philanthropist in lavender velvet who gives away exactly half of everything she earns and invests the rest with terrifying skill. Kind, sharp and impossible to swindle.',
    quote: 'Half for me, half for the world. Both halves sleep well.',
  },
} satisfies Record<string, CharacterData>;
