import type { CharacterData } from './types';

/** The Intellectual Path's characters. */
export const INTELLECTUAL = {
  quill: {
    number: 87,
    rarity: 3,
    alignment: 'Chaotic Good',
    name: 'Quill',
    fullName: 'Quilliana Fenwhistle',
    dimension: 'intellectual',
    kind: 'core',
    unlockLevel: 0,
    bio: 'Small, ink-stained to the elbows and peering through oversized spectacles, with a hat stuffed with bookmarks and a floating book that bites. Brilliant, fast-talking and endlessly curious, he footnotes his own sentences out loud.',
    quote: "Technically, and I say this with love, you're wrong.",
  },
  ottilie: {
    number: 55,
    rarity: 2,
    alignment: 'Neutral Good',
    name: 'Ottilie',
    fullName: 'Ottilie Page',
    dimension: 'intellectual',
    kind: 'recruit',
    unlockLevel: 10,
    bio: "A librarian's assistant who has read every book in one very small library, twice. Shy until you mention a book she hasn't read, and then she can't stop smiling.",
    quote: "I haven't read that one yet. Isn't that wonderful?",
  },
  thane: {
    number: 92,
    rarity: 4,
    alignment: 'Lawful Neutral',
    name: 'Magister Thane',
    fullName: 'Magister Oriel Thane',
    dimension: 'intellectual',
    kind: 'steward',
    unlockLevel: 15,
    bio: 'Tall, in robes made of paper, with a crown of quills. Polite, patient, genuinely brilliant and more than a little condescending, he speaks almost entirely in citations.',
    quote: "Please don't ask. I've already answered.",
  },
  bramble: {
    number: 58,
    rarity: 2,
    alignment: 'Neutral Good',
    name: 'Professor Bramble',
    fullName: 'Professor Mungo Bramble',
    dimension: 'intellectual',
    kind: 'recruit',
    unlockLevel: 20,
    bio: 'A rumpled botanist who argues with his own margin notes and usually loses. His pockets are full of seeds, pencils and half-finished theories.',
    quote: 'Fascinating. Wrong, but fascinating.',
  },
  nib: {
    number: 20,
    rarity: 2,
    alignment: 'Chaotic Good',
    name: 'Nib',
    fullName: 'Nib Wickett',
    dimension: 'intellectual',
    kind: 'recruit',
    unlockLevel: 7,
    bio: 'A schoolkid with ink on the nose and a satchel stuffed with questions, most of which begin with why. Nib follows Quill around like a duckling and writes down everything he says.',
    quote: 'Why? No, but WHY?',
  },
  astra: {
    number: 70,
    rarity: 2,
    alignment: 'True Neutral',
    name: 'Astra',
    fullName: 'Astra Voss',
    dimension: 'intellectual',
    kind: 'recruit',
    unlockLevel: 13,
    bio: 'A stargazer in a cloak embroidered with constellations, carrying a brass telescope everywhere, even indoors. She stays up far too late and knows the name of every star you point at.',
    quote: 'The sky is a book that turns its own pages.',
  },
  felix: {
    number: 93,
    rarity: 2,
    alignment: 'Chaotic Evil',
    name: 'Felix',
    fullName: 'Felix Rook',
    dimension: 'intellectual',
    kind: 'recruit',
    unlockLevel: 18,
    bio: 'A chess master in a checkered waistcoat and a silk cravat who plays against himself when nobody else will. He loses to himself with great panache and always kisses his own hand afterward.',
    quote: 'Check. Ah, that was me. Bravo, Felix.',
  },
  hana: {
    number: 90,
    rarity: 3,
    alignment: 'Lawful Good',
    name: 'Hana',
    fullName: 'Hana Mori',
    dimension: 'intellectual',
    kind: 'recruit',
    unlockLevel: 23,
    bio: 'A translator in a robe hung with little scroll cases, who speaks eleven languages and apologizes fluently in all of them. She collects words the way other people collect shells.',
    quote: 'Sorry. Désolé. Gomen. You get the idea.',
  },
  quimby: {
    number: 28,
    rarity: 2,
    alignment: 'Neutral Good',
    name: 'Doctor Quimby',
    dimension: 'intellectual',
    kind: 'recruit',
    unlockLevel: 26,
    bio: 'A physician in a long coat and a beaked mask stuffed with dried herbs, who looks terrifying and is the kindest healer in the land. They lecture everyone about hand-washing with enormous passion.',
    quote: "Wash your hands. That's most of medicine.",
  },
  lyra: {
    number: 23,
    rarity: 3,
    alignment: 'Chaotic Neutral',
    name: 'Lyra',
    fullName: 'Lyra Inkwell',
    dimension: 'intellectual',
    kind: 'recruit',
    unlockLevel: 30,
    bio: 'A mapmaker with rolled charts under both arms and a compass on a chain, who has walked every road she has drawn. She gets visibly upset about blank spaces on maps.',
    quote: "If it isn't on the map, go and put it there.",
  },
  solomon: {
    number: 19,
    rarity: 5,
    alignment: 'Lawful Good',
    name: 'Old Solomon',
    dimension: 'intellectual',
    kind: 'recruit',
    unlockLevel: 35,
    bio: 'A blind scholar with a long white beard and a carved cane, who memorized the great library before his eyes failed. He tells stories so vividly that listeners forget to blink.',
    quote: 'I read with my ears now. Much less eyestrain.',
  },
  hoot: {
    number: 29,
    rarity: 1,
    alignment: 'True Neutral',
    name: 'Professor Hoot',
    dimension: 'intellectual',
    kind: 'recruit',
    unlockLevel: 40,
    bio: 'An owl in a tiny red waistcoat and half-moon spectacles who lectures on everything from astronomy to soup. Pompous, adorable and occasionally asleep in the middle of his own sentences.',
    quote: 'Whooo asked? You did. Excellent.',
  },
  elowen: {
    number: 76,
    rarity: 5,
    alignment: 'Neutral Good',
    name: 'Archmage Elowen',
    dimension: 'intellectual',
    kind: 'legend',
    unlockLevel: 50,
    bio: 'An ancient wizard with a silver braid down to her knees and a staff whose crystal glows softly when she thinks. She has read everything and still asks questions like a beginner.',
    quote: "Knowledge is not a trophy. It's a lantern you keep refilling.",
  },
} satisfies Record<string, CharacterData>;
