import type { CharacterData } from './types';

/** The Occupational Path's characters. Its steward is not collectible (STORY.md §6). */
export const OCCUPATIONAL = {
  tamsin: {
    number: 84,
    rarity: 3,
    alignment: 'Neutral Good',
    name: 'Tamsin',
    fullName: 'Tamsin Brasse',
    dimension: 'occupational',
    kind: 'core',
    unlockLevel: 0,
    bio: "Soot-streaked and goggled, with a clanking tool belt and a mechanical arm she built herself. Gruff, practical and happiest mid-repair, she fixes things when she's upset, which is often.",
    quote: 'Broken. Good. Something to do.',
  },
  rivet: {
    number: 12,
    rarity: 3,
    alignment: 'Lawful Good',
    name: 'Wick',
    fullName: 'Wick Rivet',
    dimension: 'occupational',
    kind: 'recruit',
    unlockLevel: 10,
    bio: 'A lamplighter who carries a ladder everywhere and fixes the lamps nobody else notices. He has lit the same street every night for nine years.',
    quote: "Small jobs. Every night. That's the trick.",
  },
  greta: {
    number: 88,
    rarity: 1,
    alignment: 'Lawful Neutral',
    name: 'Greta',
    fullName: 'Greta Hammerfall',
    dimension: 'occupational',
    kind: 'recruit',
    unlockLevel: 20,
    bio: 'A stonemason who has spent eleven years building one wall, and is very proud of it. It is an excellent wall.',
    quote: 'One stone. Then the next one.',
  },
  sprocket: {
    number: 96,
    rarity: 1,
    alignment: 'Chaotic Good',
    name: 'Sprocket',
    dimension: 'occupational',
    kind: 'recruit',
    unlockLevel: 7,
    bio: 'An apprentice with gloves three sizes too big and a wrench nearly as long as her arm. She breaks things in the name of learning and fixes them in the name of pride.',
    quote: 'I only broke it a little!',
  },
  hilde: {
    number: 74,
    rarity: 1,
    alignment: 'Lawful Neutral',
    name: 'Hilde',
    fullName: 'Hilde Anvil',
    dimension: 'occupational',
    kind: 'recruit',
    unlockLevel: 13,
    bio: 'A blacksmith in a scorched leather apron, with arms like iron and a hammer she has named Patience. She works in steady rhythms and takes her breaks just as seriously.',
    quote: "Hit it while it's hot. Rest while it cools.",
  },
  joss: {
    number: 64,
    rarity: 1,
    alignment: 'Neutral Good',
    name: 'Joss',
    fullName: 'Joss Furrow',
    dimension: 'occupational',
    kind: 'recruit',
    unlockLevel: 15,
    bio: 'A farmer in a battered straw hat who has been up before dawn every day of his life. He is shy with people and endlessly chatty with seedlings.',
    quote: "Seeds don't plant themselves. I've asked.",
  },
  nails: {
    number: 50,
    rarity: 1,
    alignment: 'Chaotic Neutral',
    name: 'Nails',
    dimension: 'occupational',
    kind: 'recruit',
    unlockLevel: 18,
    bio: 'Spiky orange hair, a white shirt under a black jacket, and no regrets about portion sizes. The king asked for ice water and Nails served him exactly one ice cube. Fast hands, a quick laugh and a talent for doing the job to the letter.',
    quote: 'He asked for ice. He got ice.',
  },
  wilbur: {
    number: 85,
    rarity: 1,
    alignment: 'Neutral Good',
    name: 'Wilbur',
    fullName: 'Wilbur Planewright',
    dimension: 'occupational',
    kind: 'recruit',
    unlockLevel: 23,
    bio: "A carpenter with a pencil behind each ear and a saw that he keeps sharper than anyone's wit. He measures everything twice and then once more, just in case.",
    quote: 'Measure twice. Cut once. Measure again, to be safe.',
  },
  kaldoriumwarden: {
    number: 63,
    rarity: 3,
    alignment: 'Lawful Neutral',
    name: 'The Warden',
    fullName: 'The Warden of the Kaldorium',
    dimension: 'occupational',
    kind: 'recruit',
    unlockLevel: 26,
    bio: "The biggest guard in the kingdom, keeper of the Kaldorium's sand. Bald, black-bearded, belted in gold and twice the size of any man he has ever thrown out. He runs his fights by the book, and the book is very heavy.",
    quote: 'On the sand, everyone gets one fair fight. Then they get carried out.',
  },
  rosa: {
    number: 59,
    rarity: 1,
    alignment: 'Chaotic Good',
    name: 'Rosa',
    fullName: 'Rosa Gearheart',
    dimension: 'occupational',
    kind: 'recruit',
    unlockLevel: 30,
    bio: 'An inventor with a welding mask pushed up on her head, whose greatest creation is a clockwork mule that walks mostly forward. She is never discouraged, only delayed.',
    quote: 'It walks! Mostly forward!',
  },
  morrow: {
    number: 4,
    rarity: 3,
    alignment: 'Lawful Good',
    name: 'Old Morrow',
    dimension: 'occupational',
    kind: 'recruit',
    unlockLevel: 35,
    bio: 'A lighthouse keeper in a yellow raincoat with an oil lamp always in hand, who has not missed lighting the lamp for a single night in forty years.',
    quote: "Someone has to keep the light. Why not the one who's awake?",
  },
  adaeze: {
    number: 83,
    rarity: 2,
    alignment: 'Lawful Neutral',
    name: 'Guildmaster Adaeze',
    dimension: 'occupational',
    kind: 'recruit',
    unlockLevel: 40,
    bio: "The head of the Crafters' Guild, wearing a chain hung with a badge from every trade she has ever mastered. She spends her days teaching others to master theirs.",
    quote: 'Master one thing. Then help someone else master it.',
  },
  gert: {
    number: 111,
    rarity: 1,
    alignment: 'True Neutral',
    name: 'Gert',
    dimension: 'occupational',
    kind: 'recruit',
    unlockLevel: 14,
    bio: "A flat-voiced lamp-seller on a bench on Kaldor Street, and the only person in the Berserker Kingdom who has never challenged anyone to a fight. Nothing impresses him. He is, secretly, the best guide in town.",
    quote: 'Yeah, we know.',
  },
} satisfies Record<string, CharacterData>;
