import type { CharacterData } from './types';

/** The Occupational Path's characters. Its steward is not collectible (STORY.md §6). */
export const OCCUPATIONAL = {
  tamsin: {
    number: 84,
    rarity: 5,
    alignment: 'Neutral Good',
    name: 'Tamsin',
    fullName: 'Tamsin Brasse',
    dimension: 'occupational',
    kind: 'core',
    unlockLevel: 0,
    bio: "Soot-streaked and goggled, with a clanking tool belt and a mechanical arm she built herself. Gruff, practical and happiest mid-repair, she fixes things when she's upset, which is often.",
    quote: 'Broken. Good. Something to do.',
  },
  rivet: {
    number: 12,
    rarity: 5,
    alignment: 'Lawful Good',
    name: 'Wick',
    fullName: 'Wick Rivet',
    dimension: 'occupational',
    kind: 'recruit',
    unlockLevel: 10,
    bio: 'A lamplighter who carries a ladder everywhere and fixes the lamps nobody else notices. He has lit the same street every night for nine years.',
    quote: "Small jobs. Every night. That's the trick.",
  },
  greta: {
    number: 88,
    rarity: 5,
    alignment: 'Lawful Neutral',
    name: 'Greta',
    fullName: 'Greta Hammerfall',
    dimension: 'occupational',
    kind: 'recruit',
    unlockLevel: 20,
    bio: 'A stonemason who has spent eleven years building one wall, and is very proud of it. It is an excellent wall.',
    quote: 'One stone. Then the next one.',
  },
  sprocket: {
    number: 96,
    rarity: 5,
    alignment: 'Chaotic Good',
    name: 'Sprocket',
    dimension: 'occupational',
    kind: 'recruit',
    unlockLevel: 7,
    bio: 'An apprentice with gloves three sizes too big and a wrench nearly as long as her arm. She breaks things in the name of learning and fixes them in the name of pride.',
    quote: 'I only broke it a little!',
  },
  hilde: {
    number: 74,
    rarity: 5,
    alignment: 'Lawful Neutral',
    name: 'Hilde',
    fullName: 'Hilde Anvil',
    dimension: 'occupational',
    kind: 'recruit',
    unlockLevel: 13,
    bio: 'A blacksmith in a scorched leather apron, with arms like iron and a hammer she has named Patience. She works in steady rhythms and takes her breaks just as seriously.',
    quote: "Hit it while it's hot. Rest while it cools.",
  },
  joss: {
    number: 64,
    rarity: 5,
    alignment: 'Neutral Good',
    name: 'Joss',
    fullName: 'Joss Furrow',
    dimension: 'occupational',
    kind: 'recruit',
    unlockLevel: 15,
    bio: 'A farmer in a battered straw hat who has been up before dawn every day of his life. He is shy with people and endlessly chatty with seedlings.',
    quote: "Seeds don't plant themselves. I've asked.",
  },
  babette: {
    number: 50,
    rarity: 5,
    alignment: 'Lawful Good',
    name: 'Chef Babette',
    dimension: 'occupational',
    kind: 'recruit',
    unlockLevel: 18,
    bio: "A cook in a tall white hat with a wooden spoon she wields like a conductor's baton. Her kitchen runs like clockwork and smells like heaven.",
    quote: 'Everything in its place, including you.',
  },
  wilbur: {
    number: 85,
    rarity: 5,
    alignment: 'Neutral Good',
    name: 'Wilbur',
    fullName: 'Wilbur Planewright',
    dimension: 'occupational',
    kind: 'recruit',
    unlockLevel: 23,
    bio: "A carpenter with a pencil behind each ear and a saw that he keeps sharper than anyone's wit. He measures everything twice and then once more, just in case.",
    quote: 'Measure twice. Cut once. Measure again, to be safe.',
  },
  oskar: {
    number: 63,
    rarity: 5,
    alignment: 'Lawful Good',
    name: 'Oskar',
    fullName: 'Scrivener Oskar',
    dimension: 'occupational',
    kind: 'recruit',
    unlockLevel: 26,
    bio: 'A scribe who copies books by candlelight, one careful page each night. He has ink-stained fingers, a quiet voice and a library he built one page at a time.',
    quote: 'One page a night makes a library in a lifetime.',
  },
  rosa: {
    number: 59,
    rarity: 5,
    alignment: 'Chaotic Good',
    name: 'Rosa',
    fullName: 'Rosa Gearheart',
    dimension: 'occupational',
    kind: 'recruit',
    unlockLevel: 30,
    bio: 'An inventor with a welding mask pushed up on her head, whose greatest creation is a clockwork mule that walks mostly forward. She is never discouraged, only delayed.',
    quote: 'It walks! Mostly forward!',
  },
  morrow: {
    number: 4,
    rarity: 5,
    alignment: 'Lawful Good',
    name: 'Old Morrow',
    dimension: 'occupational',
    kind: 'recruit',
    unlockLevel: 35,
    bio: 'A lighthouse keeper in a yellow raincoat with an oil lamp always in hand, who has not missed lighting the lamp for a single night in forty years.',
    quote: "Someone has to keep the light. Why not the one who's awake?",
  },
  adaeze: {
    number: 83,
    rarity: 5,
    alignment: 'Lawful Neutral',
    name: 'Guildmaster Adaeze',
    dimension: 'occupational',
    kind: 'recruit',
    unlockLevel: 40,
    bio: "The head of the Crafters' Guild, wearing a chain hung with a badge from every trade she has ever mastered. She spends her days teaching others to master theirs.",
    quote: 'Master one thing. Then help someone else master it.',
  },
} satisfies Record<string, CharacterData>;
