import type { CharacterData } from './types';

/** The Physical Path's characters. */
export const PHYSICAL = {
  brannoc: {
    number: 8,
    rarity: 3,
    alignment: 'Neutral Good',
    name: 'Brannoc',
    fullName: 'Brannoc Hale',
    dimension: 'physical',
    kind: 'core',
    unlockLevel: 0,
    bio: 'A giant with a braided red beard, armor that no longer fits and a greatsword he calls Sweetheart. He is the strongest man you will ever meet, and he will tell you so, loudly, from behind the nearest wall. Brannoc talks like a champion and runs like a rabbit.',
    quote: 'Right! Who needs hitting? …Not you. You look strong.',
  },
  dessa: {
    number: 81,
    rarity: 4,
    alignment: 'Lawful Neutral',
    name: 'Dessa',
    fullName: 'Dessa Quickstep',
    dimension: 'physical',
    kind: 'recruit',
    unlockLevel: 10,
    bio: 'A courier who ran messages between towns until the roads went quiet. Wiry and sunburnt, she laces her boots twice, treats every hill as a personal challenge, and still carries one sealed letter she has never delivered.',
    quote: 'Last one to the top carries the soup.',
  },
  plush: {
    number: 62,
    rarity: 4,
    alignment: 'Lawful Neutral',
    name: 'Baron Plush',
    fullName: 'Baron Aldric Plush',
    dimension: 'physical',
    kind: 'steward',
    unlockLevel: 15,
    bio: 'Enormous, in pajamas covered in medals and a nightcap worn like a crown, carried everywhere on a sofa by four sleepwalkers. Jolly and affectionate, he calls everyone "dear" and never raises his voice.',
    quote: "Oh, don't get up. Nobody's getting up. That's the lovely part.",
  },
  harrow: {
    number: 36,
    rarity: 2,
    alignment: 'Lawful Neutral',
    name: 'Old Harrow',
    dimension: 'physical',
    kind: 'recruit',
    unlockLevel: 20,
    bio: 'A retired royal blacksmith with forearms like hams and a bad knee he refuses to discuss. He forged a great many swords in his day, and is proudest of the one that was never used.',
    quote: "Slow is fine. Stopping isn't.",
  },
  tobin: {
    number: 1,
    rarity: 2,
    alignment: 'Chaotic Good',
    name: 'Tobin',
    fullName: 'Tobin Fleet',
    dimension: 'physical',
    kind: 'recruit',
    unlockLevel: 7,
    bio: 'A skinny kid in patched shorts and a red headband who treats every road as a racetrack and every stranger as a rival. He is fast, fearless and utterly convinced that Brannoc is the bravest man alive. Nobody has managed to talk him out of it.',
    quote: "Brannoc didn't run. He carried me. That's different.",
  },
  marta: {
    number: 57,
    rarity: 2,
    alignment: 'Neutral Good',
    name: 'Marta',
    fullName: 'Marta Oakhand',
    dimension: 'physical',
    kind: 'recruit',
    unlockLevel: 13,
    bio: 'A woodcutter with two thick braids, a flannel shirt rolled to the elbows and an axe resting on one shoulder. She is slow to speak and slower to tire, and she counts her swings under her breath like a prayer.',
    quote: "A hundred swings a day. The tree doesn't care how I feel.",
  },
  bo: {
    number: 44,
    rarity: 2,
    alignment: 'Chaotic Neutral',
    name: 'Bo',
    fullName: 'Bo Tumble',
    dimension: 'physical',
    kind: 'recruit',
    unlockLevel: 18,
    bio: 'An acrobat from a circus that fell asleep mid-show, still in a striped leotard with a topknot bouncing on top. Bo cannot sit still for longer than a sneeze and turns cartwheels when happy, which is most of the time.',
    quote: 'Hands, then feet. Then hands again!',
  },
  ingrid: {
    number: 37,
    rarity: 4,
    alignment: 'Lawful Good',
    name: 'Captain Ingrid',
    fullName: 'Captain Ingrid Vale',
    dimension: 'physical',
    kind: 'recruit',
    unlockLevel: 23,
    bio: 'A guard captain in dented chainmail and a helmet with one proud red plume. She drills the whole camp at dawn with a voice like a trumpet, checks that everyone ate breakfast, and never lets anyone out of her sight. Not again.',
    quote: 'Form up. Stretch first. Complain after.',
  },
  kofi: {
    number: 51,
    rarity: 2,
    alignment: 'Lawful Good',
    name: 'Kofi',
    fullName: 'Kofi Stone',
    dimension: 'physical',
    kind: 'recruit',
    unlockLevel: 26,
    bio: 'A champion wrestler with a shaved head, gold armbands and shoulders like a doorway. He is the gentlest person in any room, and he apologizes to his opponents before every hold.',
    quote: 'Sorry in advance.',
  },
  yuki: {
    number: 78,
    rarity: 2,
    alignment: 'Neutral Good',
    name: 'Yuki',
    fullName: 'Yuki Hollowbrook',
    dimension: 'physical',
    kind: 'recruit',
    unlockLevel: 30,
    bio: 'A field medic with a dark bob and a towel always slung over one shoulder, who once swam supplies across the cold Mirrorlake when every bridge was down. Calm, unsentimental and faintly smug about her circulation.',
    quote: 'Cold water, clear head.',
  },
  sable: {
    number: 2,
    rarity: 4,
    alignment: 'Neutral Evil',
    name: 'Sable',
    dimension: 'physical',
    kind: 'recruit',
    unlockLevel: 35,
    bio: 'A masked duelist in a black cloak who practices footwork alone in the dark. Sable rarely speaks, never boasts, and has never once been seen to hurry, even while winning.',
    quote: 'Again. Slower. Now faster.',
  },
  nana: {
    number: 26,
    rarity: 2,
    alignment: 'Chaotic Good',
    name: 'Nana Birch',
    dimension: 'physical',
    kind: 'recruit',
    unlockLevel: 40,
    bio: 'A tiny, wiry grandmother in a flowered shawl who walks ten miles a day with a knobbly cane and a basket of apples. She outpaces everyone in the party and refuses to discuss her age.',
    quote: 'My knees are old. My feet never got the letter.',
  },
  aurelio: {
    number: 68,
    rarity: 5,
    alignment: 'Lawful Good',
    name: 'Aurelio',
    fullName: 'Aurelio the Unbowed',
    dimension: 'physical',
    kind: 'legend',
    unlockLevel: 50,
    bio: 'A legendary champion from before the Sleep, in golden armor that still shines, with a white beard and a great round shield. For all his fame he is humble, patient and endlessly encouraging, and he still trains every single day.',
    quote: 'Strength is not a thing you have. It is a thing you keep doing.',
  },
  aurek: {
    number: 106,
    rarity: 4,
    alignment: 'Lawful Good',
    name: 'Aurek',
    fullName: 'Aurek the Tall',
    dimension: 'physical',
    kind: 'recruit',
    unlockLevel: 25,
    bio: 'The tallest man in the kingdom, and the last to challenge its king. The king beat him in front of the whole Colosseum, and Aurek, who holds that the strongest should rule, has served him ever since without a word of complaint. Laid to rest and woken properly, he is gentle, slow to speak and very, very tall.',
    quote: 'Almost. And then, at last.',
  },
  varga: {
    number: 107,
    rarity: 3,
    alignment: 'Lawful Neutral',
    name: 'Captain Varga',
    dimension: 'physical',
    kind: 'recruit',
    unlockLevel: 22,
    bio: "Second of the horde, a scarred soldier with a story for every scar and no patience for anyone who flinches. She believes in strength, the old law and a fair fight, in that order.",
    quote: 'Strength is what lets you choose. Weak people get chosen for.',
  },
  kett: {
    number: 108,
    rarity: 2,
    alignment: 'Neutral Good',
    name: 'Kett',
    dimension: 'physical',
    kind: 'recruit',
    unlockLevel: 16,
    bio: "A young horde raider who has never once managed to \"go red\" in the battle-fury, and keeps a pressed flower from Millbrook tucked inside his armour. Loud, jumpy and far braver than he thinks.",
    quote: "Being strong isn't not being scared. It's being scared and standing there anyway.",
  },
  brunna: {
    number: 109,
    rarity: 1,
    alignment: 'Chaotic Neutral',
    name: 'Little Brunna',
    dimension: 'physical',
    kind: 'recruit',
    unlockLevel: 12,
    bio: 'A toddler in tiny armour from the Berserker Kingdom, where even the babies train. She headbutts first and asks questions never. Her grandmother says she has a great future in the arena.',
    quote: 'RAAAH.',
  },
} satisfies Record<string, CharacterData>;
