import type { CharacterData } from "./types";

/** The Physical Path's characters. */
export const PHYSICAL = {
  brannoc: {
    name: "Brannoc",
    fullName: "Brannoc Hale",
    dimension: "physical",
    kind: "core",
    unlockLevel: 0,
    bio: "A giant with a braided red beard, armor that no longer fits and a greatsword he calls Sweetheart. Loud, loyal and brave to a fault, he turns everything into a competition and would charge a castle before asking whose it was.",
    quote: "Right! Who needs hitting?",
  },
  dessa: {
    name: "Dessa",
    fullName: "Dessa Quickstep",
    dimension: "physical",
    kind: "recruit",
    unlockLevel: 10,
    bio: "A courier who ran messages between towns until the roads went quiet. Wiry and sunburnt, she laces her boots twice and treats every hill as a personal challenge.",
    quote: "Last one to the top carries the soup.",
  },
  plush: {
    name: "Baron Plush",
    fullName: "Baron Aldric Plush",
    dimension: "physical",
    kind: "steward",
    unlockLevel: 15,
    bio: 'Enormous, in pajamas covered in medals and a nightcap worn like a crown, carried everywhere on a sofa by four sleepwalkers. Jolly and affectionate, he calls everyone "dear" and never raises his voice.',
    quote: "Oh, don't get up. Nobody's getting up. That's the lovely part.",
  },
  harrow: {
    name: "Old Harrow",
    dimension: "physical",
    kind: "recruit",
    unlockLevel: 20,
    bio: "A retired blacksmith with forearms like hams and a bad knee he refuses to discuss. He stretches every morning, loudly, and expects the whole camp to join in.",
    quote: "Slow is fine. Stopping isn't.",
  },
  tobin: {
    name: "Tobin",
    fullName: "Tobin Fleet",
    dimension: "physical",
    kind: "recruit",
    unlockLevel: 7,
    bio: "A skinny kid in patched shorts and a red headband who used to run errands barefoot across three villages. He treats every road as a racetrack and every stranger as a possible rival, and he loses gracefully about half the time.",
    quote: "Race you. No, really. Race me.",
  },
  marta: {
    name: "Marta",
    fullName: "Marta Oakhand",
    dimension: "physical",
    kind: "recruit",
    unlockLevel: 13,
    bio: "A woodcutter with two thick braids, a flannel shirt rolled to the elbows and an axe resting on one shoulder. She is slow to speak and slower to tire, and she counts her swings under her breath like a prayer.",
    quote: "A hundred swings a day. The tree doesn't care how I feel.",
  },
  bo: {
    name: "Bo",
    fullName: "Bo Tumble",
    dimension: "physical",
    kind: "recruit",
    unlockLevel: 18,
    bio: "An acrobat from a circus that fell asleep mid-show, still in a striped leotard with a topknot bouncing on top. Bo cannot sit still for longer than a sneeze and turns cartwheels when happy, which is most of the time.",
    quote: "Hands, then feet. Then hands again!",
  },
  ingrid: {
    name: "Captain Ingrid",
    fullName: "Captain Ingrid Vale",
    dimension: "physical",
    kind: "recruit",
    unlockLevel: 23,
    bio: "A retired guard captain in dented chainmail and a helmet with one proud red plume. She drills the whole camp at dawn with a voice like a trumpet, then quietly checks that everyone ate breakfast.",
    quote: "Form up. Stretch first. Complain after.",
  },
  kofi: {
    name: "Kofi",
    fullName: "Kofi Stone",
    dimension: "physical",
    kind: "recruit",
    unlockLevel: 26,
    bio: "A champion wrestler with a shaved head, gold armbands and shoulders like a doorway. He is the gentlest person in any room, and he apologizes to his opponents before every hold.",
    quote: "Sorry in advance.",
  },
  yuki: {
    name: "Yuki",
    fullName: "Yuki Hollowbrook",
    dimension: "physical",
    kind: "recruit",
    unlockLevel: 30,
    bio: "A river swimmer with a dark bob and a towel always slung over one shoulder, who crossed the cold Mirrorlake every morning for twenty years. Calm, quiet and faintly smug about her circulation.",
    quote: "Cold water, clear head.",
  },
  sable: {
    name: "Sable",
    dimension: "physical",
    kind: "recruit",
    unlockLevel: 35,
    bio: "A masked duelist in a black cloak who practices footwork alone in the dark. Sable rarely speaks, never boasts, and has never once been seen to hurry, even while winning.",
    quote: "Again. Slower. Now faster.",
  },
  nana: {
    name: "Nana Birch",
    dimension: "physical",
    kind: "recruit",
    unlockLevel: 40,
    bio: "A tiny, wiry grandmother in a flowered shawl who walks ten miles a day with a knobbly cane and a basket of apples. She outpaces everyone in the party and refuses to discuss her age.",
    quote: "My knees are old. My feet never got the letter.",
  },
  aurelio: {
    name: "Aurelio",
    fullName: "Aurelio the Unbowed",
    dimension: "physical",
    kind: "legend",
    unlockLevel: 50,
    bio: "A legendary champion from before the Sleep, in golden armor that still shines, with a white beard and a great round shield. For all his fame he is humble, patient and endlessly encouraging, and he still trains every single day.",
    quote: "Strength is not a thing you have. It is a thing you keep doing.",
  },
} satisfies Record<string, CharacterData>;
