import type { CharacterData } from './types';

/** The Social Path's characters. */
export const SOCIAL = {
  pip: {
    number: 82,
    rarity: 5,
    name: 'Pip',
    fullName: 'Pip Larkspur',
    dimension: 'social',
    kind: 'core',
    unlockLevel: 0,
    bio: "Freckles, a patchwork coat and a lute with too many strings. Charming, chatty and relentlessly optimistic, Pip remembers everyone's name and has never once been still.",
    quote: "Good news: I've made a friend! Bad news: it's a goose.",
  },
  marigold: {
    number: 9,
    rarity: 5,
    name: 'Marigold',
    fullName: 'Marigold Tumble',
    dimension: 'social',
    kind: 'recruit',
    unlockLevel: 10,
    bio: 'A street juggler who drops things on purpose to make people laugh. She has never met a stranger, only friends who have not caught anything yet.',
    quote: 'Catch! No? Good. Now we are talking.',
  },
  marisol: {
    number: 13,
    rarity: 5,
    name: 'Marisol Vane',
    dimension: 'social',
    kind: 'steward',
    unlockLevel: 15,
    bio: 'The Understudy: stage makeup, a sweeping curtain cloak and a mask that shifts to look like whoever she is talking to. Sweet on the surface, cutting underneath.',
    quote: 'Oh, your life is lovely. I will take it from here.',
  },
  barnaby: {
    number: 34,
    rarity: 5,
    name: 'Barnaby',
    fullName: 'Barnaby Crumb',
    dimension: 'social',
    kind: 'recruit',
    unlockLevel: 20,
    bio: "A round, floury baker who knows everyone's usual order and everyone's birthday. His bakery door has never once been locked.",
    quote: 'Extra bun. You look like you need one.',
  },
  fitz: {
    number: 15,
    rarity: 5,
    name: 'Fitz',
    fullName: 'Fitz Tattle',
    dimension: 'social',
    kind: 'recruit',
    unlockLevel: 7,
    bio: 'A town crier with an enormous feathered hat and a brass bell, who announces everything, including things nobody asked about. Loud, loyal and a very good hugger.',
    quote: "Hear ye! Someone's awake! It's you!",
  },
  amara: {
    number: 98,
    rarity: 5,
    name: 'Amara',
    fullName: 'Amara Bright',
    dimension: 'social',
    kind: 'recruit',
    unlockLevel: 13,
    bio: "A party planner who carries confetti in every pocket and seats people so well that strangers leave as friends. She remembers everyone's favorite song.",
    quote: "Everyone belongs at the table. I'll find the chair.",
  },
  duke: {
    number: 61,
    rarity: 5,
    name: 'Duke',
    dimension: 'social',
    kind: 'recruit',
    unlockLevel: 18,
    bio: "A shaggy dog in a red bandana who adopts people rather than the other way around. He has never met anyone he didn't like, and he checks on everyone twice a day.",
    quote: "Woof. (Translation: you're family now.)",
  },
  ruth: {
    number: 53,
    rarity: 5,
    name: 'Ruth',
    fullName: 'Ruth Letterly',
    dimension: 'social',
    kind: 'recruit',
    unlockLevel: 23,
    bio: 'A postmistress with a heavy mailbag and a wonderful memory for handwriting. She has delivered every love letter in the valley and never read a single one.',
    quote: "Write to someone today. I'll carry it.",
  },
  bastian: {
    number: 67,
    rarity: 5,
    name: 'Bastian',
    fullName: 'Bastian Drum',
    dimension: 'social',
    kind: 'recruit',
    unlockLevel: 26,
    bio: 'A drummer with a big red drum strapped to his chest, who starts parades wherever he walks. People fall into step without meaning to.',
    quote: 'Everyone walks better in time.',
  },
  lola: {
    number: 35,
    rarity: 5,
    name: 'Lola',
    fullName: 'Lola Marchetti',
    dimension: 'social',
    kind: 'recruit',
    unlockLevel: 30,
    bio: 'An innkeeper with a huge wooden ladle and a bigger laugh, who feeds anyone who walks through her door. Her inn has never had a stranger in it for longer than one bowl of soup.',
    quote: 'Sit! Eat! Tell me everything!',
  },
  kitkat: {
    number: 3,
    rarity: 5,
    name: 'Kit and Kat',
    dimension: 'social',
    kind: 'recruit',
    unlockLevel: 35,
    bio: "Twins who finish each other's sentences, swap hats to confuse people and are never, ever apart. Between them they know everyone in three towns.",
    quote: "We're a... ...package deal.",
  },
  oyelaran: {
    number: 100,
    rarity: 5,
    name: 'Ambassador Oyelaran',
    dimension: 'social',
    kind: 'recruit',
    unlockLevel: 40,
    bio: 'A diplomat in a silver sash who once ended a war by inviting both armies to dinner. Charming, patient and a truly excellent cook.',
    quote: 'Nobody fights with their mouth full.',
  },
} satisfies Record<string, CharacterData>;
