import type { CharacterData } from './types';

/** The Spiritual Path's characters. */
export const SPIRITUAL = {
  wren: {
    number: 75,
    rarity: 3,
    alignment: 'Neutral Good',
    name: 'Sister Wren',
    dimension: 'spiritual',
    kind: 'core',
    unlockLevel: 0,
    bio: "A plain grey habit, a small bell and a lantern that burns brighter when she's sure of something. Gentle, stubborn and quietly funny, she tends the wounded first and listens far more than she speaks.",
    quote: "I don't know. But I'll walk with you while we find out.",
  },
  hollis: {
    number: 69,
    rarity: 5,
    alignment: 'Lawful Good',
    name: 'Hollis',
    dimension: 'spiritual',
    kind: 'recruit',
    unlockLevel: 10,
    bio: 'A quiet boy who rang the town bell every dawn, even after nobody woke to hear it. He still keeps time by it, and hums the hours under his breath.',
    quote: 'Someone should ring it. Might as well be me.',
  },
  honeywell: {
    number: 99,
    rarity: 2,
    alignment: 'Chaotic Neutral',
    name: 'Lucian Honeywell',
    dimension: 'spiritual',
    kind: 'steward',
    unlockLevel: 15,
    bio: 'The Ringmaster: a striped coat, a top hat and a candy-colored carnival that smells of spun sugar. Dazzling, flattering and restless, he is never quite satisfied.',
    quote: 'Why wait for meaning when you can have delight right now?',
  },
  sage: {
    number: 66,
    rarity: 4,
    alignment: 'Neutral Good',
    name: 'Mother Sage',
    dimension: 'spiritual',
    kind: 'recruit',
    unlockLevel: 20,
    bio: 'An old hermit who tends a garden of candles on a windy hill. She talks to the stars as if they owe her a letter, and they usually answer.',
    quote: 'Sit. The answer walks slower than you.',
  },
  moth: {
    number: 71,
    rarity: 4,
    alignment: 'Neutral Good',
    name: 'Moth',
    dimension: 'spiritual',
    kind: 'recruit',
    unlockLevel: 7,
    bio: 'A quiet temple child in a grey cloak who follows candlelight the way moths do. Moth listens more than anyone and notices the small things everyone else walks past, and once watched a stranger pray at the temple long after everyone else had gone home.',
    quote: 'Shh. Listen to the quiet.',
  },
  tuck: {
    number: 80,
    rarity: 5,
    alignment: 'Neutral Good',
    name: 'Brother Tuck',
    dimension: 'spiritual',
    kind: 'recruit',
    unlockLevel: 13,
    bio: 'A round, cheerful monk in a brown robe who treats brewing tea as a form of prayer. His kettle is always on, and nobody has ever left his fire still upset.',
    quote: 'Every cup is a small thank-you.',
  },
  zahra: {
    number: 73,
    rarity: 4,
    alignment: 'Chaotic Good',
    name: 'Zahra',
    fullName: 'Zahra of the Dunes',
    dimension: 'spiritual',
    kind: 'recruit',
    unlockLevel: 18,
    bio: 'A pilgrim in a deep blue veil with a tall walking staff, who has walked toward the sunrise every morning of her life. She travels light and laughs often.',
    quote: 'The road is the prayer.',
  },
  clementine: {
    number: 5,
    rarity: 4,
    alignment: 'Neutral Good',
    name: 'Clementine',
    fullName: 'Clementine Chime',
    dimension: 'spiritual',
    kind: 'recruit',
    unlockLevel: 23,
    bio: 'A bellmaker whose coat is sewn with dozens of tiny bells, so she jingles faintly wherever she goes. She says every bell has one true note, and she can hear yours.',
    quote: 'Every bell has one true note. So do you.',
  },
  ansel: {
    number: 39,
    rarity: 5,
    alignment: 'True Neutral',
    name: 'Ansel the Hermit',
    dimension: 'spiritual',
    kind: 'recruit',
    unlockLevel: 26,
    bio: 'A hermit who lived in a hollow oak for thirty years, with a beard long enough that small birds nest in it. Gentle, funny and completely at peace with not knowing things.',
    quote: 'I left to find myself. Turns out I was home.',
  },
  lumen: {
    number: 10,
    rarity: 1,
    alignment: 'Chaotic Good',
    name: 'Lumen',
    dimension: 'spiritual',
    kind: 'recruit',
    unlockLevel: 30,
    bio: "A lantern spirit: a small floating flame with a face, who drifted out of Sister Wren's lantern one night and never went back. Lumen glows brighter around kindness.",
    quote: "I shine. That's the whole trick.",
  },
  ilse: {
    number: 38,
    rarity: 4,
    alignment: 'Lawful Neutral',
    name: 'Abbess Ilse',
    dimension: 'spiritual',
    kind: 'recruit',
    unlockLevel: 35,
    bio: 'The stern head of a mountain abbey, in white and grey, carrying a staff carved with every name she has ever prayed for. It is a very long staff.',
    quote: 'Every name, every morning.',
  },
  oona: {
    number: 14,
    rarity: 1,
    alignment: 'True Neutral',
    name: 'Oona',
    fullName: 'Oona Farsight',
    dimension: 'spiritual',
    kind: 'recruit',
    unlockLevel: 40,
    bio: 'An oracle in a silver blindfold who sees more with it on than most people do with it off. She speaks softly and rarely, and she is almost always right about the weather.',
    quote: 'The future is shy. Be patient with it.',
  },
} satisfies Record<string, CharacterData>;
