// Generated by scripts/world-art.mjs. Do not edit by hand.

/** One walker frame, in art pixels. Feet stand 2 pixels above the bottom edge. */
export const WALKER_FRAME = { width: 16, height: 24, feet: 22 };

/** Column blocks in the sheet, three frames each: stand, step A, step B. */
export const WALKER_DIRS = ['down','up','left','right'] as const;

/** Each walker's row in assets/world/walkers.png. */
export const WALKER_ROWS = {
  brannoc: 0,
  ysolde: 1,
  quill: 2,
  wren: 3,
  oren: 4,
  pip: 5,
  tamsin: 6,
  moss: 7,
  pell: 8,
  hesper: 9,
  jory: 10,
  wenna: 11,
  oriel: 12,
  hoot: 13,
  keeper: 14,
} as const;

export type WalkerId = keyof typeof WALKER_ROWS;
