// Generated by scripts/world-art.mjs. Do not edit by hand.

/** One walker frame, in art pixels. Feet stand 2 pixels above the bottom edge. */
export const WALKER_FRAME = { width: 16, height: 24, feet: 22 };

/** Column blocks in the sheet, three frames each: stand, step A, step B. */
export const WALKER_DIRS = ['down', 'up', 'left', 'right'] as const;

/** Each walker's row in assets/world/walkers.png. */
export const WALKER_ROWS = {
  brannoc: 0,
  ysolde: 1,
  quill: 2,
  wren: 3,
  oren: 4,
  pip: 5,
  tamsin: 6,
  moss: 7,
  pell: 8,
  hesper: 9,
  jory: 10,
  wenna: 11,
  oriel: 12,
  hoot: 13,
  holt: 14,
  mira: 15,
  fen: 16,
  dunn: 17,
  bellwether: 18,
  quartermaster: 19,
  plush: 20,
  sleeper: 21,
  bo: 22,
  raider: 23,
  gert: 24,
  tessa: 25,
  barnaby: 26,
  pim: 27,
  varga: 28,
  brunna: 29,
  nana: 30,
  harrow: 31,
  hugo: 32,
  aurek: 33,
  kaldor: 34,
  shadow: 35,
  rusted: 36,
  echo: 37,
  sexton: 38,
  officer: 39,
  chaplain: 40,
  maelis: 41,
  lamplighter: 42,
  keeper: 43,
} as const;

export type WalkerId = keyof typeof WALKER_ROWS;
