// Copies the pixel icons the app uses out of the `pixelarticons` package
// (MIT, 24×24 grid) into src/components/pixel-icons.ts, so only these ship.
// Add a name to ICONS and rerun: node scripts/pixel-icons.mjs

import { readFileSync, writeFileSync } from 'node:fs';

const ICONS = [
  'user',
  'sun',
  'map',
  'script',
  'gamepad',
  'heart',
  'bell',
  'vibrate',
  'repeat',
  'upload',
  'download',
  'chevron-right',
  'zap',
];

const entries = ICONS.map((name) => {
  const svg = readFileSync(`node_modules/pixelarticons/svg/${name}.svg`, 'utf8');
  const paths = [...svg.matchAll(/<path[^>]*\sd="([^"]+)"/g)].map((m) => m[1]);
  if (!paths.length) throw new Error(`No path in ${name}.svg`);
  return `  '${name}': '${paths.join(' ')}',`;
});

writeFileSync(
  'src/components/pixel-icons.ts',
  `// Generated by scripts/pixel-icons.mjs from pixelarticons (MIT). Do not edit by hand.

/** SVG path data for each icon, drawn on a 24×24 pixel grid. */
export const PIXEL_ICONS = {
${entries.join('\n')}
} as const;

export type PixelIconName = keyof typeof PIXEL_ICONS;
`,
);
console.log(`Wrote ${ICONS.length} icons.`);
