-- Fills the username filter from the LDNOOBW English list
-- (github.com/LDNOOBW/List-of-Dirty-Naughty-Obscene-and-Otherwise-Bad-Words, CC BY 4.0),
-- lowercased with spaces and punctuation removed, since usernames are [A-Za-z0-9_].
--
-- Two kinds of match:
--   contains  the word anywhere in the name, also after undoing common letter
--             swaps (0 o, 1 i, 3 e, 4 a, 5 s, 7 t, 8 b) and dropping underscores
--   word      only as a whole part of the name, split on _ and digits. For words
--             hidden inside ordinary ones: cocoon, grape, classic, montenegro.
-- Reserved names from the first migration stay 'contains', except keeper and
-- entity, which are whole-word so goalkeeper and identity still work.

alter table public.blocked_words
  add column match text not null default 'contains' check (match in ('contains', 'word'));

insert into public.blocked_words (word, match) values
  ('2g1c', 'contains'),
  ('2girls1cup', 'contains'),
  ('acrotomophilia', 'contains'),
  ('alabamahotpocket', 'contains'),
  ('alaskanpipeline', 'contains'),
  ('anal', 'word'),
  ('anilingus', 'contains'),
  ('anus', 'word'),
  ('apeshit', 'contains'),
  ('arsehole', 'contains'),
  ('ass', 'word'),
  ('asshole', 'contains'),
  ('assmunch', 'contains'),
  ('autoerotic', 'contains'),
  ('babeland', 'contains'),
  ('babybatter', 'contains'),
  ('babyjuice', 'contains'),
  ('ballgag', 'contains'),
  ('ballgravy', 'contains'),
  ('ballkicking', 'contains'),
  ('balllicking', 'contains'),
  ('ballsack', 'contains'),
  ('ballsucking', 'contains'),
  ('bangbros', 'contains'),
  ('bangbus', 'contains'),
  ('bareback', 'word'),
  ('barelylegal', 'contains'),
  ('barenaked', 'contains'),
  ('bastard', 'contains'),
  ('bastardo', 'contains'),
  ('bastinado', 'contains'),
  ('bbw', 'word'),
  ('bdsm', 'contains'),
  ('beaner', 'contains'),
  ('beaners', 'contains'),
  ('beastiality', 'contains'),
  ('beavercleaver', 'contains'),
  ('beaverlips', 'contains'),
  ('bestiality', 'contains'),
  ('bigblack', 'contains'),
  ('bigbreasts', 'contains'),
  ('bigknockers', 'contains'),
  ('bigtits', 'contains'),
  ('bimbos', 'contains'),
  ('birdlock', 'contains'),
  ('bitch', 'contains'),
  ('bitches', 'contains'),
  ('blackcock', 'contains'),
  ('blondeaction', 'contains'),
  ('blondeonblondeaction', 'contains'),
  ('blowjob', 'contains'),
  ('blowyourload', 'contains'),
  ('bluewaffle', 'contains'),
  ('blumpkin', 'contains'),
  ('bollocks', 'contains'),
  ('bondage', 'contains'),
  ('boner', 'word'),
  ('boob', 'word'),
  ('boobs', 'contains'),
  ('bootycall', 'contains'),
  ('brownshowers', 'contains'),
  ('brunetteaction', 'contains'),
  ('bukkake', 'contains'),
  ('bulldyke', 'contains'),
  ('bulletvibe', 'contains'),
  ('bullshit', 'contains'),
  ('bunghole', 'contains'),
  ('busty', 'contains'),
  ('butt', 'word'),
  ('buttcheeks', 'contains'),
  ('butthole', 'contains'),
  ('cameltoe', 'contains'),
  ('camgirl', 'contains'),
  ('camslut', 'contains'),
  ('camwhore', 'contains'),
  ('carpetmuncher', 'contains'),
  ('chocolaterosebuds', 'contains'),
  ('cialis', 'contains'),
  ('circlejerk', 'contains'),
  ('clevelandsteamer', 'contains'),
  ('clit', 'contains'),
  ('clitoris', 'contains'),
  ('cloverclamps', 'contains'),
  ('clusterfuck', 'contains'),
  ('cock', 'word'),
  ('cocks', 'word'),
  ('coon', 'word'),
  ('coons', 'word'),
  ('coprolagnia', 'contains'),
  ('coprophilia', 'contains'),
  ('cornhole', 'contains'),
  ('creampie', 'contains'),
  ('cum', 'word'),
  ('cumming', 'word'),
  ('cumshot', 'contains'),
  ('cumshots', 'contains'),
  ('cunnilingus', 'contains'),
  ('cunt', 'contains'),
  ('darkie', 'contains'),
  ('daterape', 'contains'),
  ('deepthroat', 'contains'),
  ('dendrophilia', 'contains'),
  ('dick', 'word'),
  ('dildo', 'contains'),
  ('dingleberries', 'contains'),
  ('dingleberry', 'contains'),
  ('dirtypillows', 'word'),
  ('dirtysanchez', 'contains'),
  ('doggiestyle', 'contains'),
  ('doggystyle', 'contains'),
  ('dogstyle', 'contains'),
  ('dolcett', 'contains'),
  ('domination', 'word'),
  ('dominatrix', 'contains'),
  ('dommes', 'contains'),
  ('donkeypunch', 'contains'),
  ('doubledong', 'contains'),
  ('doublepenetration', 'contains'),
  ('dpaction', 'contains'),
  ('dryhump', 'contains'),
  ('dvda', 'contains'),
  ('eatmyass', 'contains'),
  ('ecchi', 'contains'),
  ('ejaculation', 'contains'),
  ('erotic', 'contains'),
  ('erotism', 'contains'),
  ('escort', 'word'),
  ('eunuch', 'word'),
  ('fag', 'word'),
  ('faggot', 'contains'),
  ('fecal', 'contains'),
  ('felch', 'contains'),
  ('fellatio', 'contains'),
  ('feltch', 'contains'),
  ('femalesquirting', 'contains'),
  ('femdom', 'contains'),
  ('figging', 'contains'),
  ('fingerbang', 'contains'),
  ('fingering', 'word'),
  ('fisting', 'contains'),
  ('footfetish', 'contains'),
  ('footjob', 'contains'),
  ('frotting', 'contains'),
  ('fuck', 'contains'),
  ('fuckbuttons', 'contains'),
  ('fuckin', 'contains'),
  ('fucking', 'contains'),
  ('fucktards', 'contains'),
  ('fudgepacker', 'contains'),
  ('futanari', 'contains'),
  ('gangbang', 'contains'),
  ('gaysex', 'contains'),
  ('genitals', 'contains'),
  ('giantcock', 'contains'),
  ('girlon', 'word'),
  ('girlontop', 'contains'),
  ('girlsgonewild', 'contains'),
  ('goatcx', 'contains'),
  ('goatse', 'contains'),
  ('goddamn', 'contains'),
  ('gokkun', 'contains'),
  ('goldenshower', 'contains'),
  ('goodpoop', 'contains'),
  ('googirl', 'contains'),
  ('goregasm', 'contains'),
  ('grope', 'word'),
  ('groupsex', 'contains'),
  ('gspot', 'contains'),
  ('guro', 'word'),
  ('handjob', 'contains'),
  ('hentai', 'contains'),
  ('homoerotic', 'contains'),
  ('honkey', 'contains'),
  ('hooker', 'word'),
  ('horny', 'word'),
  ('hotcarl', 'contains'),
  ('hotchick', 'contains'),
  ('howtokill', 'contains'),
  ('howtomurder', 'contains'),
  ('hugefat', 'word'),
  ('humping', 'contains'),
  ('incest', 'contains'),
  ('intercourse', 'contains'),
  ('jackoff', 'contains'),
  ('jailbait', 'contains'),
  ('jellydonut', 'word'),
  ('jerkoff', 'contains'),
  ('jigaboo', 'contains'),
  ('jiggaboo', 'contains'),
  ('jiggerboo', 'contains'),
  ('jizz', 'contains'),
  ('juggs', 'contains'),
  ('kike', 'contains'),
  ('kinbaku', 'contains'),
  ('kinkster', 'contains'),
  ('kinky', 'contains'),
  ('knobbing', 'contains'),
  ('leatherrestraint', 'contains'),
  ('leatherstraightjacket', 'contains'),
  ('lemonparty', 'contains'),
  ('livesex', 'contains'),
  ('lolita', 'contains'),
  ('lovemaking', 'contains'),
  ('makemecome', 'contains'),
  ('malesquirting', 'contains'),
  ('masturbate', 'contains'),
  ('masturbating', 'contains'),
  ('masturbation', 'contains'),
  ('menageatrois', 'contains'),
  ('milf', 'word'),
  ('missionaryposition', 'contains'),
  ('mong', 'word'),
  ('motherfucker', 'contains'),
  ('moundofvenus', 'contains'),
  ('mrhands', 'contains'),
  ('muffdiver', 'contains'),
  ('muffdiving', 'contains'),
  ('nambla', 'contains'),
  ('nawashi', 'contains'),
  ('negro', 'word'),
  ('neonazi', 'contains'),
  ('nigga', 'contains'),
  ('nigger', 'contains'),
  ('nignog', 'contains'),
  ('nimphomania', 'contains'),
  ('nipple', 'contains'),
  ('nipples', 'contains'),
  ('nsfw', 'contains'),
  ('nsfwimages', 'contains'),
  ('nude', 'word'),
  ('nudity', 'contains'),
  ('nutten', 'contains'),
  ('nympho', 'contains'),
  ('nymphomania', 'contains'),
  ('octopussy', 'contains'),
  ('omorashi', 'contains'),
  ('onecuptwogirls', 'contains'),
  ('oneguyonejar', 'contains'),
  ('orgasm', 'contains'),
  ('orgy', 'word'),
  ('paedophile', 'contains'),
  ('paki', 'word'),
  ('panties', 'contains'),
  ('panty', 'contains'),
  ('pedobear', 'contains'),
  ('pedophile', 'contains'),
  ('pegging', 'contains'),
  ('penis', 'contains'),
  ('phonesex', 'contains'),
  ('pieceofshit', 'contains'),
  ('pikey', 'contains'),
  ('pissing', 'contains'),
  ('pisspig', 'contains'),
  ('playboy', 'contains'),
  ('pleasurechest', 'contains'),
  ('polesmoker', 'contains'),
  ('ponyplay', 'contains'),
  ('poof', 'word'),
  ('poon', 'word'),
  ('poontang', 'contains'),
  ('poopchute', 'contains'),
  ('porn', 'contains'),
  ('porno', 'contains'),
  ('pornography', 'contains'),
  ('princealbertpiercing', 'contains'),
  ('pthc', 'contains'),
  ('pubes', 'word'),
  ('punany', 'contains'),
  ('pussy', 'contains'),
  ('queaf', 'contains'),
  ('queef', 'contains'),
  ('quim', 'word'),
  ('raghead', 'contains'),
  ('ragingboner', 'contains'),
  ('rape', 'word'),
  ('raping', 'word'),
  ('rapist', 'word'),
  ('rectum', 'contains'),
  ('reversecowgirl', 'contains'),
  ('rimjob', 'contains'),
  ('rimming', 'contains'),
  ('rosypalm', 'contains'),
  ('rosypalmandher5sisters', 'contains'),
  ('rustytrombone', 'contains'),
  ('sadism', 'contains'),
  ('santorum', 'contains'),
  ('scat', 'word'),
  ('schlong', 'contains'),
  ('scissoring', 'contains'),
  ('semen', 'word'),
  ('sex', 'word'),
  ('sexcam', 'contains'),
  ('sexo', 'word'),
  ('sexual', 'contains'),
  ('sexuality', 'contains'),
  ('sexually', 'contains'),
  ('sexy', 'contains'),
  ('shavedbeaver', 'contains'),
  ('shavedpussy', 'contains'),
  ('shemale', 'contains'),
  ('shibari', 'contains'),
  ('shit', 'contains'),
  ('shitblimp', 'contains'),
  ('shitty', 'contains'),
  ('shota', 'word'),
  ('shrimping', 'contains'),
  ('skeet', 'word'),
  ('slanteye', 'contains'),
  ('slut', 'contains'),
  ('smut', 'contains'),
  ('snatch', 'word'),
  ('snowballing', 'contains'),
  ('sodomize', 'contains'),
  ('sodomy', 'contains'),
  ('spastic', 'contains'),
  ('spic', 'word'),
  ('splooge', 'contains'),
  ('sploogemoose', 'contains'),
  ('spooge', 'contains'),
  ('spreadlegs', 'contains'),
  ('spunk', 'word'),
  ('strapon', 'contains'),
  ('strappado', 'contains'),
  ('stripclub', 'contains'),
  ('styledoggy', 'contains'),
  ('suck', 'word'),
  ('sucks', 'word'),
  ('suicidegirls', 'contains'),
  ('sultrywomen', 'contains'),
  ('swastika', 'contains'),
  ('swinger', 'word'),
  ('taintedlove', 'word'),
  ('tastemy', 'word'),
  ('teabagging', 'contains'),
  ('threesome', 'contains'),
  ('throating', 'contains'),
  ('thumbzilla', 'contains'),
  ('tiedup', 'word'),
  ('tightwhite', 'contains'),
  ('tit', 'word'),
  ('tits', 'word'),
  ('titties', 'contains'),
  ('titty', 'contains'),
  ('tongueina', 'contains'),
  ('topless', 'contains'),
  ('tosser', 'word'),
  ('towelhead', 'contains'),
  ('tranny', 'contains'),
  ('tribadism', 'contains'),
  ('tubgirl', 'contains'),
  ('tushy', 'contains'),
  ('twat', 'contains'),
  ('twink', 'word'),
  ('twinkie', 'word'),
  ('twogirlsonecup', 'contains'),
  ('undressing', 'contains'),
  ('upskirt', 'contains'),
  ('urethraplay', 'contains'),
  ('urophilia', 'contains'),
  ('vagina', 'contains'),
  ('venusmound', 'contains'),
  ('viagra', 'contains'),
  ('vibrator', 'contains'),
  ('violetwand', 'contains'),
  ('vorarephilia', 'contains'),
  ('voyeur', 'contains'),
  ('voyeurweb', 'contains'),
  ('voyuer', 'contains'),
  ('vulva', 'contains'),
  ('wank', 'word'),
  ('wetback', 'contains'),
  ('wetdream', 'contains'),
  ('whitepower', 'contains'),
  ('whore', 'contains'),
  ('worldsex', 'contains'),
  ('wrappingmen', 'contains'),
  ('wrinkledstarfish', 'contains'),
  ('xxx', 'contains'),
  ('yaoi', 'contains'),
  ('yellowshowers', 'contains'),
  ('yiffy', 'contains'),
  ('zoophilia', 'contains')
on conflict (word) do update set match = excluded.match;

update public.blocked_words set match = 'word' where word in ('keeper', 'entity');

-- One rule for both the trigger and the live availability check.
create or replace function public.username_blocked(name text) returns boolean
language sql stable security definer set search_path = public as $$
  with n as (
    select lower(name) as plain,
           translate(lower(name), '0134578', 'oieastb') as swapped
  )
  select exists (
    select 1 from blocked_words b, n
    where (b.match = 'contains'
           and (n.plain like '%' || b.word || '%'
                or replace(n.swapped, '_', '') like '%' || b.word || '%'))
       or (b.match = 'word'
           and (b.word = any (regexp_split_to_array(n.plain, '[_0-9]+'))
                or b.word = any (regexp_split_to_array(n.swapped, '_+'))
                or b.word = replace(n.swapped, '_', '')))
  )
$$;

revoke execute on function public.username_blocked(text) from public, anon, authenticated;

create or replace function public.check_username() returns trigger
language plpgsql security definer set search_path = public as $$
begin
  if public.username_blocked(new.username) then
    raise exception 'username_not_allowed' using errcode = 'check_violation';
  end if;
  return new;
end $$;

create or replace function public.username_available(name text) returns boolean
language sql stable security definer set search_path = public as $$
  select name ~ '^[A-Za-z0-9_]{3,16}$'
    and not exists (select 1 from profiles where lower(username) = lower(name))
    and not public.username_blocked(name);
$$;
